import type { Project, Task, Resource, Document, Announcement, DailyReport, WorkLog } from "./types"

export const mockProjects: Project[] = [
  {
    id: "proj-001",
    name: "Downtown Office Complex",
    client: "Acme Corporation",
    location: "123 Main St, Downtown",
    startDate: "2024-01-15",
    endDate: "2024-08-30",
    budget: 2500000,
    actualCost: 0,
    status: "Active",
    progress: 65,
    objectives: "Construct a modern 15-story office building with green spaces",
    milestones: ["Foundation Complete", "Structure Complete", "Interior 50%", "Completion"],
  },
  {
    id: "proj-002",
    name: "Residential Development",
    client: "BuildRight Homes",
    location: "456 Oak Avenue, Suburbs",
    startDate: "2024-02-01",
    endDate: "2024-10-15",
    budget: 3200000,
    actualCost: 0,
    status: "Active",
    progress: 45,
    objectives: "Develop 24-unit residential complex",
    milestones: ["Site Prep", "Foundation", "Framing", "Finishes"],
  },
  {
    id: "proj-003",
    name: "Highway Bridge Repair",
    client: "Department of Transport",
    location: "Route 95, Mile Marker 42",
    startDate: "2024-03-10",
    endDate: "2024-07-20",
    budget: 1800000,
    actualCost: 0,
    status: "Draft",
    progress: 0,
    objectives: "Repair and reinforcement of existing bridge structure",
    milestones: ["Inspection", "Design", "Permits", "Construction"],
  },
]

export const mockTasks: Task[] = [
  {
    id: "task-001",
    projectId: "proj-001",
    name: "Foundation Excavation",
    description: "Excavate and prepare foundation site",
    assignee: "John Smith",
    dueDate: "2024-02-28",
    status: "Completed",
    priority: "High",
    actualCost: 0,
    dependencies: [],
  },
  {
    id: "task-002",
    projectId: "proj-001",
    name: "Steel Frame Installation",
    description: "Install main structural steel framework",
    assignee: "Mike Johnson",
    dueDate: "2024-04-15",
    status: "In Progress",
    priority: "High",
    actualCost: 0,
    dependencies: ["task-001"],
  },
  {
    id: "task-003",
    projectId: "proj-001",
    name: "Electrical Rough-In",
    description: "Install electrical conduits and wiring",
    assignee: "Sarah Lee",
    dueDate: "2024-05-30",
    status: "Pending",
    priority: "Medium",
    actualCost: 0,
    dependencies: ["task-002"],
  },
  {
    id: "task-004",
    projectId: "proj-002",
    name: "Site Clearing",
    description: "Clear and level construction site",
    assignee: "Robert Davis",
    dueDate: "2024-02-15",
    status: "Completed",
    priority: "High",
    actualCost: 0,
    dependencies: [],
  },
  {
    id: "task-005",
    projectId: "proj-002",
    name: "Concrete Pour - Phase 1",
    description: "First phase concrete foundation pour",
    assignee: "David Martinez",
    dueDate: "2024-03-20",
    status: "In Progress",
    priority: "High",
    actualCost: 0,
    dependencies: ["task-004"],
  },
]

export const mockResources: Resource[] = [
  {
    id: "res-001",
    name: "Concrete Mix",
    category: "Material",
    quantity: 500,
    unit: "cubic meters",
    allocationPercentage: 90,
    cost: 125000,
  },
  {
    id: "res-002",
    name: "Steel Rebar",
    category: "Material",
    quantity: 200,
    unit: "tons",
    allocationPercentage: 90,
    cost: 360000,
  },
  {
    id: "res-003",
    name: "Excavator CAT 320",
    category: "Equipment",
    quantity: 3,
    unit: "units",
    allocationPercentage: 67,
    cost: 45000,
  },
  {
    id: "res-004",
    name: "Skilled Labor",
    category: "Labor",
    quantity: 150,
    unit: "worker-days",
    allocationPercentage: 80,
    cost: 180000,
  },
]

export const mockDocuments: Document[] = [
  {
    id: "doc-001",
    projectId: "proj-001",
    name: "Architectural Blueprints - Level 1-5",
    type: "blueprint",
    uploadDate: "2024-01-10",
    size: "12.5 MB",
    folder: "blueprints",
    uploadedBy: "Architect Team",
  },
  {
    id: "doc-002",
    projectId: "proj-001",
    name: "Building Permit",
    type: "permit",
    uploadDate: "2024-01-08",
    size: "2.3 MB",
    folder: "permits",
    uploadedBy: "City Planning",
  },
  {
    id: "doc-003",
    projectId: "proj-001",
    name: "Construction Contract",
    type: "contract",
    uploadDate: "2024-01-05",
    size: "5.8 MB",
    folder: "contracts",
    uploadedBy: "Legal Team",
  },
  {
    id: "doc-004",
    projectId: "proj-002",
    name: "Site Layout Plans",
    type: "blueprint",
    uploadDate: "2024-01-28",
    size: "8.1 MB",
    folder: "blueprints",
    uploadedBy: "Engineering Team",
  },
]

export const mockAnnouncements: Announcement[] = [
  {
    id: "ann-001",
    title: "Project Kick-Off - Downtown Office Complex",
    content:
      "All team members assigned to the Downtown Office Complex project are requested to attend the kick-off meeting tomorrow at 9:00 AM in Conference Room B.",
    datePosted: "2024-01-15T14:30:00",
    author: "Project Manager John Doe",
    priority: "high",
  },
  {
    id: "ann-002",
    title: "Safety Update",
    content:
      "Reminder: All workers must wear hard hats and safety vests at all times on site. New safety protocols in effect starting today.",
    datePosted: "2024-01-14T09:15:00",
    author: "Safety Manager",
    priority: "critical",
  },
  {
    id: "ann-003",
    title: "Weather Alert",
    content: "Heavy rain expected this weekend. Ensure all equipment is covered and site is secured properly.",
    datePosted: "2024-01-13T16:45:00",
    author: "Site Supervisor",
    priority: "normal",
  },
]

export const mockDailyReports: DailyReport[] = [
  {
    id: "dr-001",
    projectId: "proj-001",
    activities: "Continued steel frame installation on levels 3-4. Achieved 80% completion for the day.",
    issues: "Minor delay due to crane maintenance - 2 hours. Resolved by afternoon.",
    completionPercentage: 75,
    photos: [],
    submittedBy: "Mike Johnson",
    createdAt: "2024-01-13T18:00:00",
  },
]

export const mockWorkLogs: WorkLog[] = [
  {
    id: "wl-001",
    taskId: "task-002",
    date: "2024-01-13",
    hours: 8,
    notes: "Steel frame installation progressing well",
    submittedBy: "Mike Johnson",
    createdAt: "2024-01-13T17:00:00",
  },
  {
    id: "wl-002",
    taskId: "task-003",
    date: "2024-01-12",
    hours: 6,
    notes: "Site prep for electrical installation",
    submittedBy: "Sarah Lee",
    createdAt: "2024-01-12T17:00:00",
  },
]
